### ISSUE TITLE
Please tell me what's root password for  "ghcr.io/fkie-cad/fact-core-backend:4.0.1"   Thanks!

### ISSUE THREAD

**Issue by jdhellfire** [fkie-cad/FACT_docker#36] opened 2023-06-06 11:49 UTC
**When uploading the firmware package for scanning, the following error occurred:**
=======================================================
fact-backend_1   | [2023-06-05 03:08:39][fail_safe_file_operations][ERROR]: Could not write file: [Errno 13] Permission denied: '/media/data/fact_fw_data/b2'
fact-backend_1   | Traceback (most recent call last):
fact-backend_1   |   File "/usr/local/lib/python3.8/dist-packages/common_helper_files/fail_safe_file_operations.py", line 61, in write_binary_to_file
fact-backend_1   |     create_dir_for_file(file_path)
fact-backend_1   |   File "/usr/local/lib/python3.8/dist-packages/common_helper_files/file_functions.py", line 50, in create_dir_for_file
fact-backend_1   |     Path(file_path).resolve().parent.mkdir(parents=True, exist_ok=True)
fact-backend_1   |   File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
fact-backend_1   |     self._accessor.mkdir(self, mode)
fact-backend_1   | PermissionError: [Errno 13] Permission denied: '/media/data/fact_fw_data/b2'
fact-backend_1   | Process Unpacking-Worker-3:
fact-backend_1   | Traceback (most recent call last):
fact-backend_1   |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
fact-backend_1   |     self.run()
fact-backend_1   |   File "/opt/FACT_core/src/helperFunctions/process.py", line 56, in run
fact-backend_1   |     raise exception
fact-backend_1   |   File "/opt/FACT_core/src/helperFunctions/process.py", line 51, in run
fact-backend_1   |     Process.run(self)
fact-backend_1   |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
fact-backend_1   |     self._target(*self._args, **self._kwargs)
fact-backend_1   |   File "/opt/FACT_core/src/scheduler/unpacking_scheduler.py", line 64, in unpack_worker
fact-backend_1   |     extracted_objects = unpacker.unpack(fo)
fact-backend_1   |   File "/opt/FACT_core/src/unpacker/unpack.py", line 36, in unpack
fact-backend_1   |     with TemporaryDirectory(prefix='fact_unpack_', dir=self.config['data-storage']['docker-mount-base-dir']) as tmp_dir:
fact-backend_1   |   File "/usr/lib/python3.8/tempfile.py", line 919, in __init__
fact-backend_1   |     self.name = mkdtemp(suffix, prefix, dir)
fact-backend_1   |   File "/usr/lib/python3.8/tempfile.py", line 497, in mkdtemp
fact-backend_1   |     _os.mkdir(file, 0o700)
fact-backend_1   | PermissionError: [Errno 13] Permission denied: '/tmp/fact-docker-mount-base-dir/fact_unpack_tzkscdaj'
fact-backend_1   | [2023-06-05 03:08:40][process][ERROR]: Exception in Unpacking process:
fact-backend_1   | Traceback (most recent call last):
fact-backend_1   |   File "/opt/FACT_core/src/helperFunctions/process.py", line 51, in run
fact-backend_1   |     Process.run(self)
fact-backend_1   |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
fact-backend_1   |     self._target(*self._args, **self._kwargs)
fact-backend_1   |   File "/opt/FACT_core/src/scheduler/unpacking_scheduler.py", line 64, in unpack_worker
fact-backend_1   |     extracted_objects = unpacker.unpack(fo)
fact-backend_1   |   File "/opt/FACT_core/src/unpacker/unpack.py", line 36, in unpack
fact-backend_1   |     with TemporaryDirectory(prefix='fact_unpack_', dir=self.config['data-storage']['docker-mount-base-dir']) as tmp_dir:
fact-backend_1   |   File "/usr/lib/python3.8/tempfile.py", line 919, in __init__
fact-backend_1   |     self.name = mkdtemp(suffix, prefix, dir)
fact-backend_1   |   File "/usr/lib/python3.8/tempfile.py", line 497, in mkdtemp
fact-backend_1   |     _os.mkdir(file, 0o700)
fact-backend_1   | PermissionError: [Errno 13] Permission denied: '/tmp/fact-docker-mount-base-dir/fact_unpack_tzkscdaj'
fact-backend_1   | 
fact-backend_1   | [2023-06-05 03:08:40][process][WARNING]: restarting Unpacking 3 process

=======================================================

**It seems that the fact user does not have permission to operate:**

$ ls -al
total 300
drwxrwxrwt 1 root root   4096 Jun  5 03:08 .
drwxr-xr-x 1 root root   4096 Jun  5 01:48 ..
drwxr-x--- 2 root  137   4096 Jun  4 23:59 fact-docker-mount-base-dir
-rw-r--r-- 1 fact fact      0 Jun  5 01:48 fact_main_frontend.log
-rw------- 1 root root     54 Oct 13  2022 stdbool.h23t2sfcf.c
-rw------- 1 root root 285222 Oct 13  2022 tmp6p1pshvl
-rw------- 1 fact fact    151 Jun  5 02:32 tmpjerwvgx_
$   

**Please tell me what's root password for  "ghcr.io/fkie-cad/fact-core-backend:4.0.1"   Thanks a lot!**

**Comment by maringuu** [comment] 2023-10-10 07:48
Duplicate of #42

**Closed as completed by maringuu** 2023-10-10 07:48 UTC
